# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('ac_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('plant_id', models.IntegerField(default=0)),
                ('date_planted_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Soil_Moisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_value', models.FloatField(default=0)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Water_Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('water_level', models.FloatField(default=0)),
                ('wb_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weather_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ws_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='ws_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Weather_Station'),
        ),
        migrations.AddField(
            model_name='climate',
            name='ws_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Weather_Station'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Plant'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='wb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Water_Body'),
        ),
    ]
