# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20171005_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='ws_id',
            field=models.IntegerField(default=0),
        ),
    ]
