# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_auto_20171005_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator_status',
            name='status',
        ),
        migrations.AddField(
            model_name='actuator_status',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
