# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_auto_20171005_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='water_body',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='water_body',
            name='longituge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather_station',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather_station',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
