# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_remove_climate_raining'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='raining',
            field=models.IntegerField(default=0),
        ),
    ]
