# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_climate_raining'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator_status',
            name='onoff',
            field=models.CharField(default='off', max_length=10),
        ),
    ]
