# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_actuator_status_onoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil_moisture',
            name='sm_value',
            field=models.CharField(default='sufficient', max_length=250),
        ),
    ]
