# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_auto_20171023_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil_moisture',
            name='sm_value',
            field=models.FloatField(default=0),
        ),
    ]
