# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_auto_20171023_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=250)),
                ('Last_name', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=250)),
                ('Farmerid', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
