# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0012_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Farmerid',
            new_name='farmerid',
        ),
        migrations.AddField(
            model_name='plant',
            name='farmerid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plant.Farmer'),
        ),
    ]
