# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0013_auto_20171102_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmerlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.IntegerField(default=0)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='dob',
        ),
        migrations.AddField(
            model_name='farmerlogin',
            name='farmerid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plant.Farmer'),
        ),
    ]
