# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0014_auto_20171102_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator_status',
            name='ac_id',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='ac_id',
        ),
        migrations.AddField(
            model_name='actuator',
            name='mode',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3),
        ),
        migrations.DeleteModel(
            name='Actuator_Status',
        ),
    ]
