# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0015_auto_20171103_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='status',
            field=models.CharField(choices=[('N', 'ON'), ('F', 'OFF')], default='OFF', max_length=1),
        ),
        migrations.AddField(
            model_name='actuator',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='mode',
            field=models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], default='Automatic', max_length=1),
        ),
    ]
