# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0016_auto_20171103_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='mode',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=10),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3),
        ),
    ]
