# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0020_auto_20171104_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='farmerid',
        ),
        migrations.AddField(
            model_name='farmer',
            name='username',
            field=models.CharField(default='dhruv', max_length=250),
        ),
    ]
