# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0022_farmer_farmerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='pump_id',
            field=models.IntegerField(default=1),
        ),
    ]
